### ISSUE TITLE
Bugs in ggmap package affecting download_basemap()

### ISSUE THREAD

**Issue by peterdesmet** [adokter/bioRad#183] opened 2018-12-13 17:23 UTC
```R
> ppi <- project_as_ppi(example_scan)
> download_basemap(ppi)
Downloading zoom = 9 ...
Map from URL : http://tile.stamen.com/terrain/9/273/157.jpg
 Show Traceback
 
 Rerun with Debug
 Error in readJPEG(tmp) : 
  JPEG decompression error: Not a JPEG file: starts with 0x89 0x50 

> download_basemap(ppi, source = "osm")
Downloading zoom = 9 ...
Error: map grabbing failed - see details in ?get_openstreetmap.
In addition: Warning message:
In download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") :
 
 Show Traceback
 
 Rerun with Debug
 Error: map grabbing failed - see details in ?get_openstreetmap. 

> download_basemap(ppi, source = "google")
Downloading zoom = 9 ...
Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=56.364844,12.861212&zoom=9&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false'
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
 
 Show Traceback
 
 Rerun with Debug
 Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=56.364844,12.861212&zoom=9&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false' 
```

@adokter any idea what is going on here?

**Comment by adokter** [comment] 2018-12-13 18:14
I can't reproduce your first error - did you install the latest development version of ggmap? There have been changes in google maps credentials that broke ggmap, and they haven't pushed an update to CRAN yet.

The problem with osm and google are also ggmap issues, see
```
> library(ggmap)
> get_map(source="google")
Source : https://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN
Error in get_googlemap(center = location, zoom = zoom, maptype = maptype,  : 
  Forbidden (HTTP 403).
> get_map(source="osm")
Source : https://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=10&size=640x640&scale=2&maptype=terrain
Error in get_googlemap(center = location, zoom = zoom, filename = filename) : 
  Forbidden (HTTP 403).
```

**Comment by adokter** [comment] 2018-12-13 19:03
I added a version check of the ggmap package in `download_basemap`, closed by PR #185

**Comment by peterdesmet** [comment] 2018-12-13 20:02
Tested default `download_basemap()`:

1. Got error message
2. Followed ggmap installation instructions via link provided
3. Tried again.
4. Corrupt db error.
5. Restart RStudio
6. Worked.

For "osm" and "google" (expected) I got the following errors:

```R
> download_basemap(ppi, source = "google")
Downloading zoom = 9 ...
Error in if (showing_key()) { : argument is of length zero
> download_basemap(ppi, source = "osm")
Downloading zoom = 9 ...
Error: map grabbing failed - see details in ?get_openstreetmap.
In addition: Warning message:
In download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") :
  cannot open URL 'http://tile.openstreetmap.org/cgi-bin/export?bbox=12.0520521639357,55.9158385762879,13.6703726253235,56.8138491047475&scale=1200000&format=png': HTTP status was '400 Bad Request'
> 
```

I don't thinks this should block 0.4.0.

**Comment by adokter** [comment] 2019-07-23 18:06
fixed by new ggmap release

**Closed by adokter** 2019-07-23 18:06 UTC
Labels: bug
